### ISSUE TITLE
Review code for exploring data

### ISSUE THREAD

**Issue by eaferguson** [eaferguson/NWB_reproducibility#1]
I have pushed the file explore_case_data.R. This needs to be improved to:

- [ ] Add comments
- [ ] Correct scatterplots to boxplots for categorical variables
- [ ] Write the figure to a pdf file

**Comment by katiehampson1978** [comment]
All fixed and cleaned up code pushed to repo

**Comment by katiehampson1978** [comment]
Code fixed & pushed
